---
title: "Day 6"
output: html_document
---

# Review HW 4 Postponed

# Review HW 5 Postponed

# Loops and control
  - if else
  - for
    - counters (sets)
    - "growing" results
    - debugging
    - break, next

## if/else

```{r}
x <- 10

#needs to be a single logical statement - returns T or F
#if true, does the next thing (which is contained in the {})
if(x > 5) {
  x <- x^2
}

#add else 
#put ending bracket for if and starting bracket for else on the same line } else {
if(x > 5) {
  x <- x^2
} else {
  x <- x^3
}

x <- 10
if(x > 5) {
  x <- x^2
} else if(x > 3) {
  x <- x^3
} else {
  x <- x - 1
}
 
y <- TRUE

if(y) {
  hist(rnorm(1000))
}

# or if NOT y
if(!y) {
  hist(rnorm(1000))
}

# use to change or get rid of NAs
if(is.na(x)) {
  x <- NULL
}
```

## for loops

```{r}
mydf <- data.frame(x = rnorm(n = 1000, mean = 2, sd = 1), group = rep(1:10, each = 100)) 

rep(1:3, 3) #rep 1-3, 3 times
rep(1:3, each = 3) # get 1, 1, 1, 2, 2, 2,...
rep(1:3, each = 3, 2) #ditto but do that twice

this.vector <- mydf[mydf$group == 1, "x"]
my.answer <- mean(this.vector)

# MAKE IT A LOOP
for(i in 1:10) {
  print (i * 2)
}

my.answer <- vector(length = 3) # create a container before the loop
for(this.counter in 1:3) {
  this.group <- c(3, 5, 9)[this.counter]
  this.vector <- mydf[mydf$group == this.group, "x"]
  my.answer[this.counter] <- mean(this.vector)  #made a subset in my.answer to save all the answers - but need to have my.answer already set up
}
my.answer
```


# Loops practice

# GitHub

# GitHub practice
  